### ISSUE TITLE
Summer 2022 Internship Roadmap

### ISSUE THREAD

**Issue by RobotSail** [redhat-et/copilot-ops#84]
### Copilot-ops
Integrate copilot-ops into the existing workflows used by Operate-First to allow developers to quickly iterate on their work with the help of AI-assisted tooling. Learn about integrating code into the OperateFirst workflow process as well as leveraging GitHub automation tools. Evaluate the process of user interaction and make adjustments where necessary in order to improve the overall flow. Make note of incorrect generations from OpenAI and adjust the prompt or train the model in order to increase accuracy (quantified by number of iterations taken to merge a PR).

### FetchIt
Become familiar with FetchIt. Understand the difference between running an application in Kubernetes and directly on a system, and the reasons why you’d choose one over the other. Learn how to manage applications as systemd services. 

## Tasks
**Integrate copilot-ops with OperateFirst**
- [ ] Integrate copilot-ops with OperateFirst tekton
- [ ] Present copilot-ops with operate first community

**Copilot-ops CLI**
- [ ] Control the number of completions made
- [ ] Document installation process
- [ ] Output control with JSON/Text/YAML

**Copilot-ops as a Service (CaaS)**
- [ ] Integrate with OperateFirst workflows
  - [ ] Tekton pipelines
  - [ ] Probot

**Improve copilot-ops experience**
- [ ] Engineer better prompts to improve OpenAI accuracy
- [ ] Document pain points as you use copilot-ops

**Copilot-ops test modules**
- [ ] Create Golang tests for copilot-ops with Ginkgo
- [ ] Mock OpenAI server for testing outbound functionality 

**WASM Starter Guide**

- [ ] Learn the basics of WebAssembly
- [ ] Create a guide on using [AssemblyScript](https://www.assemblyscript.org/) in order to author WASM
- [ ] Develop a simple project using AssemblyScript (ideas)
  - [ ] [Fermyon](https://www.fermyon.com/)
  - [ ] Hello world Smart contract
  - [ ] Game

### **FetchIt**
- [ ] Attend FetchIt meetings to better understand the development process
- [ ] Work alongside engineers to fill in gaps
- [ ] Deploy WASM/WASI with FetchIt

### **Gain experience using various technologies**
- [ ] Familiarize with Kubernetes/OpenShift
  - [ ] Install OpenShift
  - [ ] What’s the same/different with OpenShift, K8s, MicroShift, & SingleNode OpenShift  <-this would make a great presentation, btw!
  - [ ] Clusterbot
  - [ ] KIND
- [ ] Systemd services for managing applications
- [ ] Kustomize for packaging K8s applications (operate first)
- [ ] Yaml! Lots of yaml
- [ ] Languages:
  - [ ] Python(?)
  - [ ] Golang
  - [ ] WASM
    - [ ] Rust
    - [ ] AssemblyScript
- [ ] Development environment (bash, zsh, git)

## **Community Involvement/Building**
- [ ] Find at least 1 project to become involved with
- [ ] Ideas:
  - [ ] WASM/WASI
  - [ ] KCP

### Copilot-ops CLI
- [ ] Improve code readability
- [ ] Rework OpenAI client to specify model in body
- [ ] Prompt engineering
- [ ] Lunch with [Daniel Walsh](mailto:dwalsh@redhat.com)
